### ISSUE TITLE
'file:///' protocol, subtitles cannot be loaded 

### ISSUE THREAD

**Issue by cumany** [PKM-er/media-extended#101]
Hello, this plugin is great, 
but I found some questions about subtitles.
If the video address which contain 'file:///' protocol, the subtitles cannot  loaded, but the video files    in obsidian’s vault can loaded  correctly .This seems to be a path problem,
can it be solved, thank you.

**Comment by javiavid** [comment]
I have the same problem, local subtitles are not displayed in version 3.0.0.

![image](https://github.com/PKM-er/media-extended/assets/7627504/b566b71c-e8c7-414e-b8e9-5b87fae565e9)

**Comment by aidenlx** [comment]
@javiavid could you install 3.0.1-beta.0 to see if the issue persisit? please leave new feedback in #229
