### ISSUE TITLE
Question: How to open media view

### ISSUE THREAD

**Issue by floatas** [PKM-er/media-extended#108]
Hi,

I'm new to Obsidian, I plan it to use to write notes on youtube videos and this plugin helps with that. However I'm strugling to get started with it.

How do you open media view ?

![image](https://user-images.githubusercontent.com/7883111/147702846-c28a7540-5dd0-434e-933a-d31f729ae81a.png)

Looks like same issue as in #44 , but that issue was closed without any comments.

It might be great to update wiki with that info: https://github.com/aidenlx/media-extended/wiki/Open-Links-in-One-Shared-Player

**Comment by aidenlx** [comment]
You can find a command `Media extended: Open Media from Link`, and copy the link to YouTube video to the prompt to open view

**Comment by floatas** [comment]
Happy New Year. Thank you, works perfectly.

**Comment by Elaws** [comment]
Hi,

Is there another method to open a link ? I thought we could open a link by just clicking on it : is this possible ?

Thank you !

**Comment by XMB-7** [comment]
> Hi,
> 
> Is there another method to open a link ? I thought we could open a link by just clicking on it : is this possible ?
> 
> Thank you !

You have to switch to the reading mode(using the default hotkey ctrl+e) to open an embedded video player by clicking a link, then go back to the editing mode with ctrl+e again to add timestamps. That's my workaround.

**Comment by dive2Pro** [comment]
or you can open another "Preview" mode panel for your edit panel

**Comment by EvoAlg** [comment]
So you have to be in Reading mode to have an external media link open in Obsidian, because in Preview mode it opens in a browser? That's how it works for me. It would be better just to have it open in Obsidian in Preview mode, but this seems like an Obsidian thing and not a ME things.

**Comment by joebazval** [comment]
i have the same issue de timestamp link opens in the browser not in the obsidian media viewer

**Comment by JoshuaLelon** [comment]
I also have the same issue. The timestamp link opens in the browser - not in the obsidian media viewer.

**Comment by jfines** [comment]
Its completely unusable! Nothing makes you get a timestamp to connect a note to. I added a hotkey (ctrl+m) as shown in a popular youtube video I even closed Obsidian and opened it again (restart the app) but no way to get the current timestamp put into the note. Not when hitting the hotkey, not when just start typing, nothing!

**Comment by munish259272** [comment]
After struggling for long found out this it works only in read mode
