### ISSUE TITLE
Feature Request: Insert the timestamp with reverse order.

### ISSUE THREAD

**Issue by mzwlevi** [PKM-er/media-extended#115]
Could you add a choice that can insert the timestamp with reverse order?
Such as this:
<img width="583" alt="Screen Shot 2022-02-11 at 15 55 32" src="https://user-images.githubusercontent.com/78029539/153555529-6c2eb76a-d01e-44d7-bd84-caa412bdd3c3.png">

**Comment by aidenlx** [comment]
implemented in v3, can be configured in the setting tab
