### ISSUE TITLE
Audio Record not embedding in relevant page  with Media Extended plugin enabled

### ISSUE THREAD

**Issue by gandalf34** [PKM-er/media-extended#130]
When I use the core plugin Audio Record if the media extended pluginb is enabled the recording happens and is saved as a file in the attachments folder but it cant be seen in its relevant page.

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
