### ISSUE TITLE
Hotkey Support: Feedback

### ISSUE THREAD

**Issue by aidenlx** [PKM-er/media-extended#133]
main issue for hotkey support, including global control and in-focus player control

**Comment by aidenlx** [comment]
The `C` is already working fine but there is no shortcut for the **select captions**. It could be a very powerful feature to switch between different [captions/subtitles](https://github.com/aidenlx/media-extended/wiki/Caption-Subtitle-Support). Maybe `C` could do forward cycle and the `Shift`+`C` could backward cycle. I'm using the same custom shortcut on my MPV player, it's very easy and memorable for me.

Thanks for creating this convenient extension.

_Originally posted by @pascowl in https://github.com/aidenlx/media-extended/issues/100#issuecomment-1073376820_

**Comment by aidenlx** [comment]
I am using this plugin to take notes from the youtube videos and my current workflow looks like this:

Move to media tab (where youtube video is playing)
Pause the video and grab the timestamp using the hotkey
Write the the note about that timestamp
Move back to the media tab and play the video
Repeat again from step 1
This process is cumbersome as we have to jump between the tabs oftentimes. It would be much easier if we control the media/video playback from the tab where we are writing the note.

Possible solution: Ability to add the hotkey/shortcut to control the media playback from anywhere inside the obsidian

If anyone has a better workflow please let me know

_Originally posted in #127

**Comment by d0verenny** [comment]
This plugin absolutely needs an update. The lack of the ability to rewind is so frustrating.

**Comment by chaecramb** [comment]
Was going to make a FR, but just came across this existing one. 

So just to say I totally agree, hotkey support to play/pause, skip forward/back without having to be focused on the media player would be fantastic!

**Comment by Asatoshi314** [comment]
There is a Edge/Chrome browser plugin called Slid which is a perfect realization of this feature. Aside from hotkey control, this plugin also support capture current video footage and automatically paste the screenshot into your note, which is another great feature.
Chrome plugin shop page: https://chrome.google.com/webstore/detail/slid-youtube-screenshot-n/cgajiilhmpfemmdihjnodpibaffakjhj

**Comment by Elaws** [comment]
Great FR. Are there any news on V3 availability ?

**Comment by t-ober** [comment]
Is there at least an option to play/pause toggle when focusing on the media extended tab, or a way to enable that in the current version?
