### ISSUE TITLE
Some YouTube URLs do not play within Obsidian for Windows

### ISSUE THREAD

**Issue by billng** [PKM-er/media-extended#141]
Whether it is \[ ](url) format or \!\[ ](url) format, some YouTube URLs do not play within Obsidian for Windows. But they both work fine in Obsidian for Android. May I ask, what is this problem?

Can not play
https://www.youtube.com/watch?v=gkq3oEH6huM

![image](https://user-images.githubusercontent.com/9856151/175895935-0e9274ed-fdbc-4770-982c-4c0623a8a595.png)

Works fine
https://www.youtube.com/watch?v=4VRcQ0svoCY

![image](https://user-images.githubusercontent.com/9856151/175896080-43e44642-b187-48d7-a8a9-7ef82cdba308.png)

**Comment by aidenlx** [comment]
dup of #173
