### ISSUE TITLE
How do I install the (incomplete) v3 version?

### ISSUE THREAD

**Issue by MiracleXYZ** [PKM-er/media-extended#183]
This project has been inactive for nearly one year. Although the full features of v3 have yet to be completed, v2 is way too outdated as of now (June 2023). 

Can you provide instructions on how to build, install, and contribute to v3 ourselves? Many thanks!

**Comment by bonecast** [comment]
bumping for this.

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.

**Comment by Dennyyusuf** [comment]
> Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Stay tuned!

Thank you very much. Any ETA on this beta release?

**Comment by aidenlx** [comment]
v3 beta.0 is now available in BRAT, you can use "PKM-er/media-extended" to join beta testing :)

**Comment by MiracleXYZ** [comment]
> v3 beta.0 is now available in BRAT, you can use "PKM-er/media-extended" to join beta testing :)
> 
> PS: mobile support is not yet available

Good news! Gonna check it out immediately :)

**Comment by Dennyyusuf** [comment]
> v3 beta.0 is now available in BRAT, you can use "PKM-er/media-extended" to join beta testing :)
> 
> PS: mobile support is not yet available
Thank you for this great plugin! 
Will you consider mobile support soon?

**Comment by aidenlx** [comment]
> Will you consider mobile support soon?

maybe in next minor version, it won't be worked on in v3.0 beta testing

**Comment by aidenlx** [comment]
v3 has landed, please make sure to check for latest update
