### ISSUE TITLE
[BUG] Player layout issues in v3

### ISSUE THREAD

**Issue by zuluwi** [PKM-er/media-extended#193]
Video is not displayed at full player size
![resim](https://github.com/PKM-er/media-extended/assets/111116092/417c7911-de6f-4e2b-87f0-0fdf2e33bcb9)
![resim](https://github.com/PKM-er/media-extended/assets/111116092/39920a92-12a2-4887-b720-895c3cf83d25)
with native controls:
![resim](https://github.com/PKM-er/media-extended/assets/111116092/320d6791-084c-450f-8366-e2cc0a796d07)

also can't click the "Skip Ad" button on Youtube videos

**Comment by aidenlx** [comment]
noted, already fixed in next release :)

**Comment by zuluwi** [comment]
Thanks for fixing it! But the "Skip Ad" button still seems to be buggy.

**Comment by aidenlx** [comment]
Could you provide the video you’re testing with?

**Comment by zuluwi** [comment]
> Could you provide the video you’re testing with?


https://github.com/PKM-er/media-extended/assets/111116092/fdde6a76-308c-4f32-bc95-0c7cfac2fd89

**Comment by aidenlx** [comment]
You can show website controls from more options menu of media view to skip ad. I'll try if there's an automated way to do that.
