### ISSUE TITLE
【播放器】v3 播放器使用网站播放器后，无法返回到插件播放器

### ISSUE THREAD

**Issue by juestchaos** [PKM-er/media-extended#194]
使用
Show website native controls
如何回到插件插件自己的播放器

**Comment by aidenlx** [comment]
我放在view的more menu里了，我还是改成不在播放器的菜单显示，统一在leaf的more options里显示吧😂

**Comment by aidenlx** [comment]
![Image](https://github.com/PKM-er/media-extended/assets/31102694/e0958c71-d66c-4916-887f-d2ccc706021d)
