### ISSUE TITLE
[FR] Allow working on notes without "media" property in v3

### ISSUE THREAD

**Issue by zuluwi** [PKM-er/media-extended#196]
As far as I understand from v3, to be able to use timestamp or snapshot command from the playing media, the player tab or a note file whose `media` property matches the link in the player must be active at that moment. As an alternative to this, I would like to suggest a workflow that allows you to interact with more than one player in any note.

In this video there is an edit I tried in another plugin to work with multiple players

https://github.com/PKM-er/media-extended/assets/111116092/03863d85-7d50-41f5-a3e5-f2ef2006e0fd

The most recently 
- opened, 
- clicked, 
- or interacted with (play/pause/pause/jump with timestamp link or manually, etc.) 

tab among the player tabs is set as the **"Focused Player"**. This tab may have a different icon or title to make it easier to identify which tab it is.

Commands such as 
- player control commands, 
- save snapshot command, 
- or get timestamp link command 

are executed on the **"Focused Player"**. A command can be added to switch between players to select the player to interact with while working on the note file.

**Comment by aidenlx** [comment]
you can try new logic of control latest media from arbitrary note. the target media is marked as red icon in tab header: 
![154391707039568_ pic](https://github.com/PKM-er/media-extended/assets/31102694/22d136bd-5b75-4613-ab15-5eef28516962)

**Comment by zuluwi** [comment]
Thank you very much for your hard work! 🙏 

In addition to these
- Can you add a command to select another tab without having to click on the player tab?
- After closing the active tab, the icon of the new active tab is not updated, is it possible to set the new active tab in the `onClose` method?

**Comment by aidenlx** [comment]
> Can you add a command to select another tab without having to click on the player tab?

Do you mean revealing non-active tab from tab group when executing commands? It would be better if you could illustrate in more details. 

> After closing the active tab, the icon of the new active tab is not updated, is it possible to set the new active tab in the onClose method?

Nice catch! Will be fixed soon.

**Comment by zuluwi** [comment]
> Do you mean revealing non-active tab from tab group when executing commands? It would be better if you could illustrate in more details.

A command to select the next tab from the current active tab among the player tabs, so that you can continue taking notes without having to click with the mouse.


https://github.com/PKM-er/media-extended/assets/111116092/dbfcc912-7fa9-4507-bf10-1b400ede9427

**Comment by aidenlx** [comment]
> A command to select the next tab from the current active tab among the player tabs, so that you can continue taking notes without having to click with the mouse.

this should be a feature request. if you have time, you may open another issue to keep this tracked better :) other bugs you've mentioned have been fixed in alpha3

**Comment by zuluwi** [comment]
> this should be a feature request.

oh, I see
> other bugs you've mentioned have been fixed in alpha3

Thank you so much 🙏
