### ISSUE TITLE
v3 beta7 部分B站视频无法使用截图

### ISSUE THREAD

**Issue by juestchaos** [PKM-er/media-extended#207]
v3 beta7
视频可以正常播放
但是点击截图按钮后，没有任何反应，时间戳正常的
控制台报错如下：
![image](https://github.com/PKM-er/media-extended/assets/241007/f5b7b1f1-9206-4819-8693-a4ee20bc4cfb)

**Comment by juestchaos** [comment]
截图功能可以使用时间戳有记录
但是在笔记页面渲染不出来截图样式

![image](https://github.com/PKM-er/media-extended/assets/241007/17ba4ef0-64c4-408e-8782-2dfa8512d2ff)

**Comment by aidenlx** [comment]
把data.json删了试下，默认模板有差异，新版需要 `!{{SCREENSHOT}}` 才能插入embed
