### ISSUE TITLE
FR: Open media in single shared player

### ISSUE THREAD

**Issue by javiavid** [PKM-er/media-extended#210]
When you are researching a topic it is very common to have a note with multiple timestamps from different videos. Every time you click on a timestamp a tab opens in obsidian and this clutters the obsidian interface a lot.

Would it be possible to only have an option for a single player so that regardless of the video it always loads in the same player?

Thanks for continuing development!

**Comment by aidenlx** [comment]
you can assign a hotkey to "take timestamp" or "screenshot" command, so when focused in note, the active player with icon marked red will be used as target player

**Comment by javiavid** [comment]
Thanks for the response, maybe I didn't understand you correctly.

The idea is that a single player can watch multiple different videos, as would happen in a desktop video player or a YouTube playlist.
Is this possible?

Currently, if you want to see timestamps of several videos, this happens.:
![image](https://github.com/PKM-er/media-extended/assets/7627504/1f2a5fea-887d-4b2b-9d51-a9cb6e310a1c)

**Comment by aidenlx** [comment]
in beta10, you can use pin command to let media open in single player

![CleanShot 2024-02-16 at 15 01 00@2x](https://github.com/PKM-er/media-extended/assets/31102694/4d741a70-3ee9-4482-9f3a-cbcdff64d950)

**Comment by javiavid** [comment]
Thanks!
