### ISSUE TITLE
Viemo -> Vimeo Typo

### ISSUE THREAD

**Issue by Comprehensive-Jason** [PKM-er/media-extended#211]
There's a recurring typo turning Vimeo into Vimeo.

For instance, the login webpage selector displays `Viemo`. 

![image](https://github.com/PKM-er/media-extended/assets/68677082/ff7c2a8b-e1e5-46e9-851e-cab62283f9c9)

Clicking on it brings you to `https://www.viemo.com`, which is not a valid video website.

Is this intended, or should I make a pull request correcting all instances of `viemo` to `vimeo` in the code?
![image](https://github.com/PKM-er/media-extended/assets/68677082/75c995b5-ab34-4eb5-98a2-4a05675513d0)

**Comment by aidenlx** [comment]
Nice catch! Fixed in beta7
