### ISSUE TITLE
v3 beta7 视频链接选择一直使用相关模式打开时弹出空白窗口。

### ISSUE THREAD

**Issue by phantasy36** [PKM-er/media-extended#212]
在阅读模式下，视频链接上单击右键选择alway open https://域名 as regular video后右边弹出一个新分栏窗口，此分栏窗口为空白窗口没有任何内容，必须关闭后再次在阅读模式点击视频链接才能新弹出一个新分栏窗口打开视频。
建议：如果不能自动判断模式，那么选择打开模式时不要新弹出窗口。或者弹出时也要同时打开视频，不然需要关闭新弹出窗口后再次打开才能正常使用。

**Comment by phantasy36** [comment]
> 可以在新的库里录屏复现一下吗，我不清楚你具体的情况没复现出来，至少要提供你的笔记内容

![1](https://github.com/PKM-er/media-extended/assets/46774023/cd30aebc-b627-4e00-993e-1b7a7ae4a657)

**Comment by aidenlx** [comment]
> 另外，是否可以增加截图的格式选择，webp格式不能上传到图床。。。

beta9可以选格式

> 再就是大概什么时候能够与图床对接，实现直接上传到自己的图床？

这个没有计划支持，最好找图床插件上传本地文件

**Comment by phantasy36** [comment]
> 这个没有计划支持，最好找图床插件上传本地文件

obsidian有一个支持本地图片上传的插件，但是截图这样的支不支持暂时不确定，需要beta9版本可以选择格式输出后再看。可能是因为我的图床不支持webp格式吧。谢谢，辛苦了。
