### ISSUE TITLE
Beta10 - Open media with url not working well

### ISSUE THREAD

**Issue by javiavid** [PKM-er/media-extended#214]
-Open media
-Paste URL
-Enter

Instead of opening a panel with the video, the Windows file explorer opens

**Comment by aidenlx** [comment]
please provide the url you're using

**Comment by javiavid** [comment]
https://www.youtube.com/watch?v=DTcJmIbn5nw

**Comment by aidenlx** [comment]
will be fixed in next beta

**Comment by aidenlx** [comment]
fixed in beta11

**Comment by javiavid** [comment]
Fixed file explorer issue. Now the video player opens.

Maybe I don't remember it well, but I think that before when you ran open media it added the YouTube link to the note. Has this changed?

![image](https://github.com/PKM-er/media-extended/assets/7627504/dcfea9f1-0a7a-46e4-b34e-3f06d155f70b)

**Comment by aidenlx** [comment]
no it only do so when creating a timestamp from the player
