### ISSUE TITLE
Beta10 - The screenshot is not shown when capturing

### ISSUE THREAD

**Issue by javiavid** [PKM-er/media-extended#215]
The configuration is by default.
The file is created on the hard drive, but does not appear in the note.

I have tried changing the format and it has changed the template.

https://github.com/PKM-er/media-extended/assets/7627504/fe65691b-ae70-43fd-99e7-6f5dfbf9a2f0

**Comment by aidenlx** [comment]
the default template has changed, you can fix this by simply replacing `{{SCREENSHOT}}` with `!{{SCREENSHOT}}` in template
