### ISSUE TITLE
Beta10 - Two suggestions for interaction

### ISSUE THREAD

**Issue by QSC707** [PKM-er/media-extended#218]
After the video starts playing or the playback control component on the cover will block the video content, which will affect the viewing experience

1. The video cover does not display the playback control component by default. Hover over the video cover to display the playback control component
2. Hide the playback control component immediately when the mouse moves out of the video range

**Comment by aidenlx** [comment]
as long as you click away from player, it will work :)


https://github.com/PKM-er/media-extended/assets/31102694/cc927890-46cb-4a7b-9356-571f24c96bf0
