### ISSUE TITLE
【beta.11】播放器“pin”模式即使是同一个视频也会完全重新加载

### ISSUE THREAD

**Issue by bcdax110** [PKM-er/media-extended#220]
在播放器[固定](https://github.com/PKM-er/media-extended/issues/210#issuecomment-1947855335)后，
同一个视频不同时间戳的跳转也会完全重新加载整个播放器，
而取消固定后就可以直接调转到指定时间，不需要重新加载整个播放器

**Comment by aidenlx** [comment]
fixed in beta12
