### ISSUE TITLE
I just upgraded to 3.0 and all previous videos embedded using URLs according to the rules of this plugin are no longer available

### ISSUE THREAD

**Issue by TheCodeverse** [PKM-er/media-extended#228]
I just upgraded to 3.0 and all previous videos embedded using URLs according to the rules of this plugin are no longer available, and new embedded videos are not available. I had to re-embed using Youtube's embed code, but there are thousands to deal with. Any ideas on how to fix this?

**Comment by aidenlx** [comment]
could you provide examples of embed urls that no longer valid?

**Comment by TheCodeverse** [comment]
I just got the plugin update and the video embedding issue is fixed, thanks!
