### ISSUE TITLE
local subtitles failed to load

### ISSUE THREAD

**Issue by qiekqiek** [PKM-er/media-extended#229]
如果库的子文件夹里只有一个视频一个字幕，那就正常，能播放、能从定位打开、能字幕，否则就是Failed toload"视频.mp4"Cannot read properties of undefined（reading'split')。

**Comment by aidenlx** [comment]
请提供你受影响文件夹内的所有文件的完整文件路径，以及使用的系统版本和obsidian版本

**Comment by aidenlx** [comment]
could you install 3.0.1-beta.0 to see if the issue persisit?

**Comment by javiavid** [comment]
Tested in 3.0.1-beta.0 and the subtitles do not appear.

**Comment by aidenlx** [comment]
could you check if is there any error in console?

**Comment by javiavid** [comment]
![image](https://github.com/PKM-er/media-extended/assets/7627504/f2394c38-9302-4653-800f-d90476343550)

**Comment by qiekqiek** [comment]
> 请提供你受影响文件夹内的所有文件的完整文件路径，以及使用的系统版本和obsidian版本 Please provide the complete file paths of all files in your affected folder, as well as the system version and obsidian version used

**Comment by qiekqiek** [comment]
> 请提供你受影响文件夹内的所有文件的完整文件路径，以及使用的系统版本和obsidian版本 Please provide the complete file paths of all files in your affected folder, as well as the system version and obsidian version used

不是字幕srt，是有多个mp4文件时，mp4就打不开。

**Comment by qiekqiek** [comment]
> 你能安装 3.0.1-beta.0 看看问题是否持续吗？

3.0.1-beta.0没这个bug了，多视频也能打开了，也能加载字幕

**Comment by javiavid** [comment]
path:
d:\localtest

I attach the video and the SRT for testing.
https://drive.google.com/file/d/1sOGGqpX82_MruzlDwMRcZI-Qb9auDAa5/view?usp=sharing

SYSTEM INFO:
	Obsidian version: v1.5.6
	Installer version: v1.5.3
	Operating system: Windows 10 Pro 10.0.22631
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 4
	Plugins enabled: 2
		1: BRAT v0.8.4
		2: Media Extended v3.0.1-beta.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by aidenlx** [comment]
@javiavid could you try close all opened leaves and install beta1 to see if it works? I've add extra debug info in this version, so post your console logs when you open that media

**Comment by javiavid** [comment]
It didn't work..
Uninstall the plugin and delete all notes

![image](https://github.com/PKM-er/media-extended/assets/7627504/532e7787-6d32-42b5-a55b-2ad09b7d9c32)

**Comment by aidenlx** [comment]
Could you demonstrate how you pick the file? Are you coping file path, or using file picker? It would be better if you could record how exactly do you open the file, this could provide more information.

**Comment by javiavid** [comment]
I was dragging it from Windows Explorer with the CTRL key pressed and it didn't work, but if I do it with the "Open media" option it works.
I think it would be great if it could be done by dragging, but at least for now it works.

Thank you for your interest in solving it.

**Comment by aidenlx** [comment]
@javiavid please open a separate FR describing the specific workflow of drag and drop to open media in details, and where did you drag file into.

**Comment by javiavid** [comment]
I have detected an error with the file name.

1 video.mp4 (subtitles shown)
1. video.mp4 (subtitles not displayed)

The error is the period in the name.
