### ISSUE TITLE
Feature: Play Video from Local Drive

### ISSUE THREAD

**Issue by aidenlx** [PKM-er/media-extended#23]
- [x] playback (`![](files:///example.mp4)`)
- [x] Add video folder as a shortcut
- [x] Batch edit when root path is changed

**Comment by Vuccappella** [comment]
Would love the ability to open local files.

**Comment by adeluccar** [comment]
Same. I have a System/Files folder where I add all my images and local videos.

I'd like to be able to open a video from that folder to add timestamp notes. 

Anyone know how to do this?

**Comment by MicReed** [comment]
期待这个功能，有很多本地的视频需要stamp

**Comment by yslemmo** [comment]
> 

file://[本地文件链接]可以打开

**Comment by aidenlx** [comment]
implemented in v3 "custom protocol" feature
