### ISSUE TITLE
Bug: Subtitle does not appear when there are several local videos

### ISSUE THREAD

**Issue by javiavid** [PKM-er/media-extended#231]
Subtitle does not appear when there are several local videos

Steps:
- Open media: select first video
- Play in video player
- Open media: select second video
- Play in video player

Only with the first video are the subtitles shown. If you reload the first video after the second, the subtitles are not displayed either.

In reality it only works the first time you load a local video, if you load another video even from another folder it doesn't work either.

To reset the player and make it work again, only the first local video, you must upload an online video.

**Comment by aidenlx** [comment]
1. check if problem exists in latest beta
2. create a minimal vault that can reproduce the issue and upload the vault

**Comment by javiavid** [comment]
The problem continues in 3.0.1-beta.2
I attach the vault and the videos (they are the same but with different names)

https://drive.google.com/file/d/1tDovbIn42IhqF0uiefMMMzM5g9Tl9wjT/view?usp=sharing

**Comment by aidenlx** [comment]
could you check if it's fixed in beta4?

**Comment by javiavid** [comment]
3.0.2-beta.0
The error continues

**Comment by aidenlx** [comment]
Are subtitles load properly when inside vault?

**Comment by aidenlx** [comment]
please check 3.0.2-beta.1 and post console log output when testing

Uploading CleanShot 2024-02-21 at 11.30.48 - 01.mp4…

**Comment by javiavid** [comment]
3.0.2-beta.1

I am attaching a video so you can see what happens and the log file generated.

In the video you can see several things:

- The first local video shows the subtitles
- The second local video does not show the subtitles (because it is the second, not because it cannot read them)
- Reset with a YouTube video
- The YouTube video only shows 1 frame and stops
- The second video now does show the subtitles.


https://github.com/PKM-er/media-extended/assets/7627504/7d125a8a-674f-4d4a-aacf-ca275e770570



[obsidian.md-1708500671314.log](https://github.com/PKM-er/media-extended/files/14355881/obsidian.md-1708500671314.log)

**Comment by javiavid** [comment]
I attach a screenshot of the unfold error

![image](https://github.com/PKM-er/media-extended/assets/7627504/722e9baa-fbaf-4167-8d3f-542b62ddf8c4)

**Comment by javiavid** [comment]
3.0.2 beta 2
It works!
