### ISSUE TITLE
[FR] Please add the option to open media in new pane to the side

### ISSUE THREAD

**Issue by maximbelyayev** [PKM-er/media-extended#233]
When using command "Media Extended: Open media", please provide an option to open the media in a panel to the side. I have an existing template for videos and triggering the command in a note should open the media as shown below:

<img width="2193" alt="Screenshot 2024-02-19 at 11 27 47 AM" src="https://github.com/PKM-er/media-extended/assets/105830732/626a8fb6-d99f-4171-9a75-a185474c9bc7">

This way, I'm able to open media in a note I've already created, or use it when creating a new note from Templater. Plugin "Timestamp Notes" accomplishes this, which I currently use as a substitute.

I believe this was the default behavior before 3.0. Currently, with this release we are forced follow this plugin's random workflow which is opening a media in a new full-size window, and having to click a star to creating a "Media note":

<img width="2193" alt="Screenshot 2024-02-19 at 11 30 33 AM" src="https://github.com/PKM-er/media-extended/assets/105830732/a8c1dd12-5950-4d24-a6df-b214013904f0">

The plugin is great and your work is much appreciated, but please at least provide this option, or provide an option for creating a template / working with Templater.  Thanks!

**Comment by maximbelyayev** [comment]
As an aside, for those interested I also modified styles.css so that media is centered in the pane.

Before: ```.mx .data-\[view-type\=video\]\:aspect-video[data-view-type=video]{aspect-ratio:16 / 9}```

After: ```.mx .data-\[view-type\=video\]\:aspect-video[data-view-type=video]{aspect-ratio:16 / 9;display:inline;}```

**Comment by aidenlx** [comment]
open media command is using the same logic as quick switcher, you need to use mod keys with enter to open to the side
![CleanShot 2024-02-29 at 15 58 33@2x](https://github.com/PKM-er/media-extended/assets/31102694/1c234325-fb32-476e-bb1e-6b56aa4e90ba)
