### ISSUE TITLE
【Bug】插件导致某些文件打不开

### ISSUE THREAD

**Issue by likemuuxi** [PKM-er/media-extended#236]
当我启动 media-extended 时某些文件不再可以打开

弹出问题框如下：
![image](https://github.com/PKM-er/media-extended/assets/85612715/b19e0cb7-87c8-4f8b-a8a4-b41b69eaed56)

问题文件如下（应为md文件）：
[02_系统调用.txt](https://github.com/PKM-er/media-extended/files/14343410/02_.txt)

**Comment by aidenlx** [comment]
fixed in 3.0.1 beta3
