### ISSUE TITLE
3.0.1-beta.3 - Error importing external local video

### ISSUE THREAD

**Issue by javiavid** [PKM-er/media-extended#237]
When you import a video from "open media" and select a local video from folder, it does not open in the player and this error appears in the latest version 3.0.1-beta.3.

<img width="223" alt="image" src="https://github.com/PKM-er/media-extended/assets/7627504/c455b07d-a450-47b1-866e-69c5b8a576ef">

**Comment by aidenlx** [comment]
can't repro, could you provide location path of the vault?

**Comment by javiavid** [comment]
Create a new vault and install the plugin and it works fine.
