### ISSUE TITLE
[Feature Request] Allow direct copying of timestamps/screenshots

### ISSUE THREAD

**Issue by PennHui666** [PKM-er/media-extended#238]
## Issue Summary
It is not very convenient to go through media note every time you take a timestamp/timestamped screenshots, because not all video files require media note. For some simple records, you just need to copy the timestamp to the required markdown file.

## Proposed Improvement
Allow timestamps/timestamped screenshots to be captured directly into the clipboard or at the cursor position within a document tab, enabling users to paste them directly where needed without having to copy from a media note.

**Comment by aidenlx** [comment]
![CleanShot 2024-02-21 at 02 31 21@2x](https://github.com/PKM-er/media-extended/assets/31102694/62679d1f-a362-448c-b8d6-ee7ba294a7ed)
