### ISSUE TITLE
[FR] 将添加时间戳命令（快捷键）根据时间戳要添加的位置分成两个

### ISSUE THREAD

**Issue by bcdax110** [PKM-er/media-extended#246]
现在添加时间戳的逻辑似乎有两种：
- 在编辑器活跃的时候：在当前文件位置添加时间戳
- 在视频播放器活跃的时候：添加到生成 Media Note 文件里

但是添加时间戳的命令只有一个。如果在按照前一种逻辑使用的时候，不小心点了视频播放器，再按快捷键添加时间戳会忽然冒出一个文件，时间戳就会添加到新创建的文件里，而不是预期的添加在打开的笔记文件中。

**Comment by aidenlx** [comment]
预计下个版本添加额外的“加入 Media Note ”命令，原先命令在播放器中改为最近活跃的markdown编辑器
