### ISSUE TITLE
Get current timestamp of recording not available in v3

### ISSUE THREAD

**Issue by nilAlex** [PKM-er/media-extended#249]
The command for "Get current timestamp of recording" is no longer showing up in v3.0.2 update. I can no longer do timestamps on active audio recordings. Is this feature being removed?

**Comment by aidenlx** [comment]
It’s not yet implemented. Will be ported from earlier version in next few versions :)

**Comment by nilAlex** [comment]
Amazing, I am missing that feature so much

**Comment by aidenlx** [comment]
available in v3.1.0-beta.2, also add support for canvas :)
