### ISSUE TITLE
Allow more granular playback speed control via keyboard shortcuts - especially between 1x and 2.5x

### ISSUE THREAD

**Issue by cocofoco** [PKM-er/media-extended#251]
First of all, amazing plugin. Works seamlessly and makes video note-taking, both online and offline, a smooth and pleasant experience. Thank you for working on this.

**The problem**: 
AFAIK, at the moment, playback speed can be `0.25x, 0.5x, 0.75x, 1x, 1.25x, 1.5x, 2x, 3x, 5x, 10x, custom`. But speeds like `1.6x` or `2.1x` are not supported when using the keyboard shortcuts.
This can be quite frustrating because different content creators speak at different speeds, or some videos are less or more information dense, thus requiring faster or slower playback. Depending on the video and the creator I am watching I may need a playback speed of `1.7x` or `1.4x` or even `2.2x`, sometimes changing speed even during the same video.

**Proposed solution**:
Allow the user to have more granular control over the playback speed. Allow increases of `0.1x` or even `0.05x`, especially in the `0.5x - 3x` range.

**Comment by aidenlx** [comment]
command `increase/decrease speed by 0.1x` is included in 3.0.3-beta.1
