### ISSUE TITLE
[Bug][3.0.3 beta] 无法加载本地视频

### ISSUE THREAD

**Issue by juestchaos** [PKM-er/media-extended#254]
复现条件选择的是，本地移动硬盘中的视频
如出现如下提示，如图
控制台无报错，不知道是格式问题，还是中文路径过长问题
![image](https://github.com/PKM-er/media-extended/assets/241007/c5e5d9d1-eaf9-413e-9482-aeacdff361d9)

**Comment by aidenlx** [comment]
库的路径和文件的路径？

**Comment by juestchaos** [comment]
文件路径
我看弹出的提示，显示的文件路径
file://E:/巧虎/01、巧虎大陆版【巧虎乐智小天地】/03、幼幼版（2-3岁）/2021年持续更新中/幼幼版2021年01月-《好吃的食物》.mp4

**Comment by aidenlx** [comment]
> **库的路径**和文件的路径？
