### ISSUE TITLE
[Bug][3.0.3beta] 播放网络视频会会在播放开始先显示一层模糊遮罩

### ISSUE THREAD

**Issue by juestchaos** [PKM-er/media-extended#255]
前几个版本没有这个问题
播放B站视频发现会先播放一段模糊遮罩的内容

如图
![image](https://github.com/PKM-er/media-extended/assets/241007/54857896-8a04-4acc-9222-7204977d97b4)

**Comment by aidenlx** [comment]
这个是故意这么设计的
