### ISSUE TITLE
Broken I frames

### ISSUE THREAD

**Issue by HippyCraig** [PKM-er/media-extended#260]
My issue which occured on two different machines was that the iFrame wouldnt render, a suggestion on Discord was to try turning off Media Extended and in doing so, iFrames started to work again.  Below is some screen shots I took before disableling the plugin.  I am on hte latest build 1.5.8

![image](https://github.com/PKM-er/media-extended/assets/17074456/7c513d80-0cb4-4c63-a103-9eda3f59983b)
![image](https://github.com/PKM-er/media-extended/assets/17074456/0abb0ffd-e15d-4381-9e76-c311f3ab9d2a)

**Comment by aidenlx** [comment]
context needed, please provide detailed reproduction steps (screen recording if possible), related note content if any, console log, environment, plugin version, and try to reproduce this in a sandbox vault.

PS: update to latest plugin first

**Comment by aidenlx** [comment]
May related #234

**Comment by HippyCraig** [comment]
So prior to 1.5.8 upgrade I had 1.5.6 I believe was the number.  I enabled your plugin a while back and everthing was fine below 1.5.8 of Obsidian.  When that upgraded to the current iFrames stopped rendering at all.  The screen shots in the orginal post show what my iFrame looked like in source mode.  When I flipped to read mode, the iFrames didnt render anymore so as far as the page was concered nothing was there from the looks of it.  Looking at the console in the dev tool on the reading view shows the above issue I was seeing.  When I disabled your plugin my iFrames instantly rendered.  Maybe something was introduced in 1.5.8 that doesnt jive with Media Extended, is my best guess.

**Comment by aidenlx** [comment]
please update to latest version of **the media extended plugin** and create a new vault with the embed and plugin to check if this issue persists. also upload the note content with issue.

**Comment by aidenlx** [comment]
fixed in 3.0.4

**Comment by HippyCraig** [comment]
Its working again, thank you.
