### ISSUE TITLE
[bug] 在笔记区域无法使用快捷键

### ISSUE THREAD

**Issue by bcdax110** [PKM-er/media-extended#264]
似乎从v3.0.3-beta.0版本开始，在普通笔记里面无法使用快捷键，只能点击视频播放器才能使用快捷键操作

**Comment by aidenlx** [comment]
请提供完整的在新库中的复现步骤，并录屏演示

**Comment by bcdax110** [comment]
在沙盒仓库测试的，只有Meida Extend插件（3.0.4），
这次演示的快捷键是播放暂停<key>Ctrl</key>+<key>Alt</key>+<key>Space</key>（但是其他快捷键也一样）
这次试的时候发现如果是开一个tab的模式（`New tab`）就没有这个问题，如果是开一个新的窗口（`New window`）就有这个问题
视频如下（一开始焦点在文本编辑器的时候快捷键没有效果，后面点了视频播放器再按快捷键就有效果）
https://github.com/PKM-er/media-extended/assets/15951421/1a7653d5-13a1-41ed-b260-2828040d6361
