### ISSUE TITLE
Problems opening a local file

### ISSUE THREAD

**Issue by karamazoffm** [PKM-er/media-extended#277]
When opening a local file, the total duration often contains incorrect data and there is no possibility of interactive scrolling (only with hot keys)
![Рис 002](https://github.com/PKM-er/media-extended/assets/146418188/297e145f-253b-41cd-b335-71669aeb80eb)

**Comment by aidenlx** [comment]
Please test the file with plugin disabled first in sandbox vault, and provide sample media file that can reproduce the issue.

**Comment by aidenlx** [comment]
Close due to inactivity
