### ISSUE TITLE
期望能加入默认播放速度与一倍速的切换命令

### ISSUE THREAD

**Issue by kandeyuan-yuan** [PKM-er/media-extended#279]
期盼着，期盼着，插件终于更新且加入了倍速功能，对于考试一族来说是刚需啊，感谢作者。
使用场景，考试一族，因为时间紧，通常用倍速播放学习视频（例如1.5倍速）。然而，倍速播放视频时，有时会听不清，需要回退几秒，用正常速度（例如一倍速）重新播放。因此期望能有切换命令，在自定义的快速播放速度（例如1.5倍速），与正常播放速度(1倍速)之间切换。
类似potplayer播放器中，快捷键“Z”，可以在自定义播放速度与一倍速播放速度之间来回切换。
1，能否自定义播放速度。
2，自定义播放速度与正常播放速度之间来回切换。
3，能否自定义回退视频时间，默认是5秒，我一般设置是4秒。虽然相差只有一秒，积少成多。。。而且如果可以自定义可以更灵活一些些，例如在做一些英语听力练习时。

再次感谢作者提供这么伟大强大的插件，在我心里排名是插件市场前3强，谢谢您。

**Comment by aidenlx** [comment]
加了个长按快进的选项，v3.0.5-beta5可以试一下
