### ISSUE TITLE
[FR] 允许用户自定义播放速度的增减步长

### ISSUE THREAD

**Issue by XMB-7** [PKM-er/media-extended#293]
对于命令Increase/Decrease playback speed by x0.1, 就我个人而言可能更习惯于单次加减x0.25, 无论是中英都比较合适. 所以如果能在插件设置页面里将该0.1变量化, 即允许用户自定义, 那就最好不过了.

**Comment by qiekqiek** [comment]
急着用的话，可以去设置里面自己搜索替换
