### ISSUE TITLE
突然出现了截图提示错误提示。

### ISSUE THREAD

**Issue by phantasy36** [PKM-er/media-extended#294]
1、之前一直使用正常，今天使用突然发现了播放黑屏，打时间戳没有问题，但是截图就提示错误。
<img width="209" alt="image" src="https://github.com/PKM-er/media-extended/assets/46774023/1a9b4a89-7d3b-47c3-8e96-2011b073126b">

我的设置如下：
<img width="582" alt="image" src="https://github.com/PKM-er/media-extended/assets/46774023/ac559c3b-2a3e-4e66-9071-8761211fda17">

2、之前给作者您反馈过调整进度声音自动降低到50%。您反馈说是我自建服务的问题，您在chrome下访问也有这个问题。但是我在Windows11下用edge和chrome浏览器访问了自建服务，发现没有问题，不管如何调整都不会降低音量。
![1](https://github.com/PKM-er/media-extended/assets/46774023/126cd527-4357-4375-9fcd-e230d3467cce)

**Comment by aidenlx** [comment]
同前，先试直链
