### ISSUE TITLE
升级到3.0.7后，库外的本地视频做的时间戳点了没反应

### ISSUE THREAD

**Issue by eric209** [PKM-er/media-extended#298]
今天升级到3.0.7后，库内的本地视频做时间戳一切正常，库外的本地视频时间戳，点击无反应。请问怎么解决，谢谢！
3.0.6与3.0.7的时间戳链接见下面。

**Comment by eric209** [comment]
![PixPin_2024-03-17_21-38-15](https://github.com/PKM-er/media-extended/assets/29397511/c92bd251-8f91-447a-82fa-26e2ab718cc6)
![PixPin_2024-03-17_21-35-02](https://github.com/PKM-er/media-extended/assets/29397511/a761ee40-d57e-4070-82f6-1c3b53d30511)

**Comment by aidenlx** [comment]
在3.1.0beta修复了，可以先安装试下

**Comment by eric209** [comment]
已解决，谢谢！！！！！
