### ISSUE TITLE
[bug] 在右窗格中打开bilibili视频, 网页控件开启后不可见, 必须切换到标签页或下窗格重新开启, 切换回去又不可见.

### ISSUE THREAD

**Issue by XMB-7** [PKM-er/media-extended#299]
比如想要开启b站的弹幕和字幕, 就会遇到这一问题, 而youtube视频则正常.
![recording](https://github.com/PKM-er/media-extended/assets/65625632/62d7ffad-1c3b-49d5-a3ff-69203eeee75f)

**Comment by aidenlx** [comment]
把窗口拉宽才会显示，b站的问题

**Comment by XMB-7** [comment]
发现使用hover editor完美解决, 比如为其设置默认的浮窗尺寸为800*600, 然后把视频页面转为浮窗时, 宽度直接就够显示出b站的控件了. 所以如果能直接提供用浮窗打开视频页面的功能, 使用起来就异常方便了, 详见#226.
