### ISSUE TITLE
[FR] 已经存在的时间戳批量支持视频网站原生时间戳

### ISSUE THREAD

**Issue by bcdax110** [PKM-er/media-extended#304]
#284 提到的网站原生时间戳在新添加时间戳时会自带，但是在此之前添加的时间戳并不会附带网站原生时间戳。

希望可以添加一个命令，用来转换当前文件中那些没有添加网站原生时间的时间戳

**Comment by aidenlx** [comment]
这个没计划支持，你看下批量替换能不能解决

**Comment by bcdax110** [comment]
好的，用`\[(.+)\]\(https://www\.bilibili\.com/video/BV1yE411Z7AP\?p=(\d+)#t=(.+)\)`规则替换成`[$1](https://www.bilibili.com/video/BV1yE411Z7AP?p=$2&t=$3#t=$3)`似乎可以解决
