### ISSUE TITLE
[Bug] 视频播放完成后再点击时间戳，视频会从头开始播放，而不是从时间戳对应的位置播放

### ISSUE THREAD

**Issue by bcdax110** [PKM-er/media-extended#305]
[Bug] 视频播放完成后再点击时间戳，视频会从头开始播放，而不是从时间戳对应的位置播放

出现问题所处的情况：
- 使用的是播放器“Pin模式”
- bilibili 视频
- 视频播放完成（即出现推荐视频的的状态）
- 点击的时间戳是当前播放的视频
   - 点击时间戳后，播放器时间先是时间戳对应的时间，然后立刻变成 0:00
   - 备注：如果点击的时间戳不是当前视频，能跳转到正常的位置

**Comment by bcdax110** [comment]
顺便一提，有时时候（可能是pin模式，并且切换视频后）右下角的按钮工作不太正常，全屏按钮没有效果，三个点的那个按钮需要退出全屏才能看到弹出来的菜单

**Comment by aidenlx** [comment]
未发布的下个版本已经修复

**Comment by aidenlx** [comment]
> 顺便一提，有时时候（可能是pin模式，并且切换视频后）右下角的按钮工作不太正常，全屏按钮没有效果，三个点的那个按钮需要退出全屏才能看到弹出来的菜单


单独开个issue

**Comment by bcdax110** [comment]
> > 顺便一提，有时时候（可能是pin模式，并且切换视频后）右下角的按钮工作不太正常，全屏按钮没有效果，三个点的那个按钮需要退出全屏才能看到弹出来的菜单
> 
> 单独开个issue

已开：#308
