### ISSUE TITLE
无法截屏，提示如图所示，还请排查问题，辛苦了

### ISSUE THREAD

**Issue by FeiLZX3Km** [PKM-er/media-extended#306]
![image](https://github.com/PKM-er/media-extended/assets/21981195/d7a49f9b-8d6d-4abd-8392-011418ec67a6)

**Comment by aidenlx** [comment]
![CleanShot 2024-03-21 at 01 00 51@2x](https://github.com/PKM-er/media-extended/assets/31102694/a29d60dd-c334-4323-88ba-76c922b523df)

试下这个
