### ISSUE TITLE
How to disable autoplay of media in notes

### ISSUE THREAD

**Issue by wongtx** [PKM-er/media-extended#316]
如题。每次打开包含媒体链接的笔记时，其内的视频都会自动播放。我并不希望这样
此外，感谢您对这个插件的开发，给我提供了很多的便利

**Comment by aidenlx** [comment]
context needed, please provide detailed reproduction steps (screen recording if possible), related note content if any, console log, environment, plugin version, and try to reproduce this in a sandbox vault.

PS: update to latest plugin first

**Comment by wongtx** [comment]
https://github.com/PKM-er/media-extended/assets/46996862/fcbf8625-a720-40ba-8dbb-b52927b49837
I hope that every time you open this tab, the video link will not start playing automatically. 
Can you give me a hand?

**Comment by wongtx** [comment]
I found that the problem did not seem to be caused by media extended.

**Comment by wongtx** [comment]
I found out why. 
It is caused by the linkcard plug-in.
https://github.com/chenghongyao/obsidian-linkcard-plugin
