### ISSUE TITLE
Disable screen dimming when video is paused.

### ISSUE THREAD

**Issue by TonyAtlas** [PKM-er/media-extended#319]
Thanks for the great plugin!

I often take screenshots of an area of the screen using a third-party program.
Most of my pictures are black and white. Thanks to the Minimal theme setting "Blend images in light mode", my images blend into the background and it looks very aesthetically pleasing.

When I watch a video through your plugin and press pause to take a screenshot, the picture is slightly darker.
I didn't notice it at first because it's not a big difference, but eventually all the screenshots I take while paused are darker and don't blend into the background like they would if I took a screenshot while the video was playing.
Now I can see a darker background in the pictures and also on this darkening sometimes you can see some details of the picture worse.

This darkening also generally degrades the image quality.

I attach a picture of how it looks like. I have the same 2 pictures here. The first one was taken after pressing pause and the second one was taken while playing a video.

Could you add an option to disable this effect? 

![Pic_20240329_161911](https://github.com/PKM-er/media-extended/assets/82872888/bb46df7e-7fbd-4aea-bbc6-b289bdb3445b)

**Comment by aidenlx** [comment]
it may be theme issue, could you create a new vault with your theme config to reproduce this issue? (or you can just copy `.obsidian` folder of your current vault to new vault)

**Comment by TonyAtlas** [comment]
> it may be theme issue, could you create a new vault with your theme config to reproduce this issue? (or you can just copy `.obsidian` folder of your current vault to new vault)

Checked on another storage with my configuration. Also tried to reproduce it in the default theme.

Same effect everywhere.

It doesn't seem to be a problem in the theme.

It's just that when I hit pause or hover over the window where the video is playing, it darkens slightly and a play bar appears at the bottom. 

I think this is a standard effect. There is a similar effect in YouTube, when watching a video in the browser, you also point your mouse at the video while it is playing. But in YouTube only the bottom part of the video is darkened at that moment.

**Comment by aidenlx** [comment]
Could you test which kind of media is affected? provide a new vault with media file or url that could reproduce the issue could be very helpful.

**Comment by TonyAtlas** [comment]
> Could you test which kind of media is affected? For example, only YouTube is affected, or local file/vimeo is affected as well. provide a new vault with media file or url that could reproduce the issue could be very helpful.

Of course!

This problem is visible on both local video files and YouTube. It is especially visible on videos with white backgrounds.

For example, [this video](https://youtu.be/8c6Peo0ychw?si=54G4XpH0DUXAlPCL&t=480) from the 8th minute has a white background and you can see this darkening better on it. 

Maybe even on some monitors it is less noticeable. But anyway the difference in the screenshots is obvious.

I attach one more frame, where the screenshot that was made during playback is on top and the one that was made during pause is on the bottom.

![Pic_20240329_192305](https://github.com/PKM-er/media-extended/assets/82872888/5d3c505e-244f-4c45-b61f-ce3b03491549)

You can see even on this video what part of the screen I captured.
