### ISSUE TITLE
Feature request: don't take over youtube links, add a youtube link to media viewer

### ISSUE THREAD

**Issue by notuntoward** [PKM-er/media-extended#325]
This is the best youtube annotator I've seen on Obsidian, but after using it a while, I have a couple requests:

1.  Don't always send youtube links clicks to this plugin's media viewer window

When I click on a youtube link, the media window always opens up instead of the youtube on the web browser.  I'd most often want to instead go directly to the browser, because it's bigger, and because I can block ads there (when this plugin's media viewer opens up, it's a least a minute before the ads finish playing).  

For this reason alone, I've had to disable this plugin.  I only re-enable it when I want to take youtube notes.  I didn't need to disable [Timestamp Notes plugin](https://github.com/juliang22/ObsidianTimestampNotes), for example

2. Add a timestamped youtube link in the media viewer.  

For the reasons above, viewing videos in the browser is better.  I'd like to get there directly from the media viewer, at the timestamp shown on the viewer.  A "show in browser" button, or something like that, would be handy.

**Comment by aidenlx** [comment]
There are ad block built-in for YouTube, could you check which version of plugin you're using?

For window size issue, simply drag tab with player out to dedicated window will give you freedom to control video size.

If you do want to open url in browser, you can right click to select "open in browser"
