### ISSUE TITLE
[FR]视频按住屏幕加速等

### ISSUE THREAD

**Issue by kongyuan** [PKM-er/media-extended#327]
1. 希望视频有左键按住屏幕加速和按住光标键加速的功能, 类似B站网页, 可在设置中调速, 默认x3
2. 希望take timestamp in media note 不需要focus在视频窗口就可以使用, 换句话说即便focus在视频笔记中,直接按快捷键就可以执行此命令, 另外自动focus在新添加的note的时间戳后面, 同时暂停视频, 
3. 希望播放/暂停命令可以有分开的版本, 单独控制播放以及暂停
4. 焦点bug, 空格本是用来暂停用的, 但是当用鼠标点过全屏按钮之后, 按空格会操作是否全屏而非暂停, 可能其他按钮也会有这个问题
5. bug, 全屏模式下右下角三个点点了没反应

**Comment by qiekqiek** [comment]
记者用的话，第二点可以用quickadd自己设置

**Comment by kongyuan** [comment]
> 记者用的话，第二点可以用quickadd自己设置

就是希望用原生的, 我个人认为这应该是插件的一部分, 体验会好很多.

**Comment by aidenlx** [comment]
第一个功能有快捷键，触屏的暂时还没有特别优化的精力 <https://mx.pkmer.net/zh-CN/reference/commands#:~:text=Fast%20forward%20at%20~x%20by%20holding%20hotkey>

第二、三、四个最好单独开个issue

第五个之前有issue #308
