### ISSUE TITLE
我点击时间戳五角星自动生成md

### ISSUE THREAD

**Issue by powerHourse** [PKM-er/media-extended#377]
![Uploading iShot_2024-06-02_20.34.23.png…]()
记得之前都是在打开的md文件中插入对应时间戳， 但是现在会生成视频文件名字对应的md文件，并把时间戳录入进去

**Comment by powerHourse** [comment]
![iShot_2024-06-02_20 34 23](https://github.com/PKM-er/media-extended/assets/13093736/5707eeee-cc81-4f6d-a3f0-4e9e76e1e553)

**Comment by powerHourse** [comment]
重新开关几次ob就好了

**Comment by XMB-7** [comment]
因为那个图标按钮就是故意设计成生成新md的, 想在当前md文档里插入时间戳, 自己给相应命令设置快捷键然后使用.

**Comment by powerHourse** [comment]
> 因为那个图标按钮就是故意设计成生成新md的, 想在当前md文档里插入时间戳, 自己给相应命令设置快捷键然后使用.

了解，感谢回复。
