### ISSUE TITLE
Better Footnote quick fix PLEASEEEEEEEE

### ISSUE THREAD

**Issue by Paining1** [PKM-er/media-extended#410]
Hello sir, I am very sorry to be asking you this here. I love your plugin better footnote. Can you please fix better footnote to work inside tabs plugin. Please!!! It already works in callouts, but it fails to work inside other embeds I think.

**Comment by Comprehensive-Jason** [comment]
Hover preview for footnotes is now a core Obsidian feature, [implemented in 1.6](https://obsidian.md/changelog/2024-06-07-desktop-v1.6.2/). 

That's why he stopped updating the plugin, because it's not necessary anymore.

**Comment by Paining1** [comment]
Ahh thank you
