### ISSUE TITLE
Feature: Touch Gestures

### ISSUE THREAD

**Issue by dummifiedme** [PKM-er/media-extended#75]
While using the plugin on iPAD, there should be a way to skip forwards or backwards like in a YouTube video. Even while using YouTube player, I couldn’t enable it. It would be really essential while taking notes. If I have to insert timestamp about something which just passed, I would need to skip backwards. I can do it using the plyr buttons, but still double taps would be much more convenient and faster.

I don’t have much idea, but looking at plyr, it seems like it might even have this feature?

**Comment by aidenlx** [comment]
Done in v3
