### ISSUE TITLE
Feature: Global hotkeys for extended video controls

### ISSUE THREAD

**Issue by Vuccappella** [PKM-er/media-extended#77]
Give us the ability to manipulate all the controls of the video player with hotkeys. 

If you've ever used a browser extension called 'Video Speed Controller' you'd know what I'm talking about.

For example, it would be very useful if I could bind keyboard shortcuts to jump forward or backwards on the video player using say 'x' and 'c' (in 5s or 10s increments) on my keyboard while the player is focused.

Also adjusting the speed of the player using 's' and 'd' in 0.10speed increments (or any other hotkey you want.)

Currently when watching a video in the player and taking notes side by side you have to control all of these with your mouse, go back with your mouse, go forward etc. If you're using the youtube player you have some built-in shortcuts but those aren't very handy.  It's very handy to be able to rewind a piece of content while you're taking notes, speed up the boring parts or slow down passages only with a few key-presses. 

Ideally the hotkeys we bind to control the players can be assigned to simple letters like s/d/x/c etc and that doesn't interfeer with global hotkeys or the use of these keys and they only work when the player itself is focused.

**Comment by cogscides** [comment]
It's 100% missing. Especially needing to pause, but I think that will be resolved all together.

**Comment by Elaws** [comment]
Great idea, came here to suggest the same thing.

Ability to fast forward/backward with right/left arrow, pause with space and go full screen with F, as with YouTube, would be really awesome.

It's been 6 months since it was suggested, are there any news on that feature ?

Thanks a lot ;)

**Comment by aidenlx** [comment]
implemented in v3
